const TRAIT_LABELS = [
  '秀麗','なし','醜悪',
  '高貴の出','なし','下賎の出',
  '都会育ち','なし','田舎育ち',
  '裕福','なし','貧乏',
  '厚き信仰','なし','不心得者',
  '誠実','なし','不実',
  '冷静沈着','なし','猪突猛進',
  '貪欲','なし','無欲',
  '献身的','なし','利己的',
  '秩序派','なし','混沌派',
  '進取派','なし','保守派',
  '神経質','なし','鈍感',
  '好奇心旺盛','なし','無頓着',
  '過激','なし','穏健',
  '楽観的','なし','悲観的',
  '勤勉','なし','遊び人',
  '陽気','なし','内気',
  '派手','なし','地味',
  '高慢','なし','謙虚',
  '上品','なし','粗野',
  '武骨','なし','繊細',
  '硬派','なし','軟派',
  'お人好し','なし','ひねくれ者',
  '名誉こそ命','なし','愛に生きる'
];

const TRAIT_EN_MAP = {
  '秀麗':'Good-looking', '醜悪':'Ugly',
  '高貴の出':'Noble Birth', '下賎の出':'Humble Origin',
  '都会育ち':'City Raised', '田舎育ち':'Country Raised',
  '裕福':'Wealthy', '貧乏':'Poor',
  '厚き信仰':'Devout', '不心得者':'Irreligious', '不信得者':'Irreligious',
  '誠実':'Sincere', '不実':'Insincere',
  '冷静沈着':'Calm and Collected', '猪突猛進':'Rash',
  '貪欲':'Greedy', '無欲':'Content',
  '献身的':'Self-sacrificing', '利己的':'Selfish',
  '秩序派':'Lawful', '混沌派':'Chaotic',
  '進取派':'Progressive', '保守派':'Conservative',
  '神経質':'Neurotic', '鈍感':'Insensitive',
  '好奇心旺盛':'Curious', '無頓着':'Indifferent',
  '過激':'Radical', '穏健':'Moderate',
  '楽観的':'Optimistic', '悲観的':'Pessimistic',
  '勤勉':'Diligent', '遊び人':'Pleasure-seeker',
  '陽気':'Cheerful', '内気':'Shy',
  '派手':'Flashy', '地味':'Plain',
  '高慢':'Arrogant', '謙虚':'Humble',
  '上品':'Refined', '粗野':'Coarse',
  '武骨':'Blunt', '繊細':'Sensitive',
  '硬派':'Earnest', '軟派':'Flirtatious',
  'お人好し':'Good-natured', 'ひねくれ者':'Cynical',
  '名誉こそ命':'Lives for Honor', '愛に生きる':'Lives for Love'
};
